# -*- coding: utf-8 -*-
"""csv creator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trIDMn_LukiUrs5OfbvVWjOAa1neOFPg
"""

import pandas as pd
import random
from datetime import datetime, timedelta

# 1. Setup Configuration
num_rows = 5000  # Generating slightly more than 4500 to be safe
products = [
    'Orthopedic Mattress', 'Supreme Foam', 'Memory Foam Pillow',
    'Spring Mattress', 'Sofa Cushion', 'Comforter Set'
]
platforms = ['Facebook', 'Instagram', 'Website Review']

# 2. Comment Templates & Keywords (Based on your Proposal)
# We mix these to create unique-looking comments.

positive_templates = [
    "Honestly the best investment for my back. The {product} is amazing.",
    "Finally getting good sleep thanks to Swan's {product}.",
    "Delivery was super fast and the {product} quality is top notch.",
    "I was skeptical but the {product} is very comfortable.",
    "Highly recommend the {product}, worth every taka.",
    "Great service and the {product} feels premium.",
    "My parents love the {product} I bought them.",
    "Soft yet firm. The {product} is perfect.",
]

negative_templates = [
    "Disappointed with the {product}. It started sagging after two months.",
    "The {product} is too hard, waking up with back pain.",
    "Delivery for my {product} was delayed by a week. Unacceptable.",
    "Not happy with the foam density of the {product}, feels cheap.",
    "Customer service didn't reply when I asked about my {product} warranty.",
    "The {product} smells like chemicals even after a week.",
    "Don't buy the {product}, it captures too much heat.",
    "My {product} arrived damaged and return process is a nightmare.",
]

neutral_templates = [
    "What is the price of the {product}?",
    "Do you have a showroom in Dhanmondi to test the {product}?",
    "Is the {product} available in King Size?",
    "Does the {product} come with a warranty?",
    "Can I pay in installments for the {product}?",
    "What are the dimensions of the {product}?",
    "Comparing the {product} vs your competitor, which is better?",
    "Restock update for the {product}?",
]

# 3. Generator Function
data = []

for _ in range(num_rows):
    # Select Product and Platform
    prod = random.choice(products)
    platform = random.choice(platforms)

    # Generate Date (Random date within last 12 months)
    days_offset = random.randint(0, 365)
    date_event = datetime.today() - timedelta(days=days_offset)
    date_str = date_event.strftime("%Y-%m-%d")

    # Determine Sentiment (Weighted: 45% Positive, 35% Negative, 20% Neutral)
    # We bias slightly towards positive/negative to give your NLP model something to chew on.
    sentiment_roll = random.random()

    if sentiment_roll < 0.45:
        sentiment = "Positive"
        comment = random.choice(positive_templates).format(product=prod)
    elif sentiment_roll < 0.80: # 35% Negative (0.45 to 0.80)
        sentiment = "Negative"
        comment = random.choice(negative_templates).format(product=prod)
        # Add specific "foam density" complaint occasionally as per your proposal
        if "foam" in prod.lower() and random.random() < 0.2:
            comment = f"I am facing specific foam density issues with the {prod}. It sinks too much."
    else:
        sentiment = "Neutral"
        comment = random.choice(neutral_templates).format(product=prod)

    data.append([date_str, platform, prod, comment, sentiment])

# 4. Create DataFrame
df = pd.DataFrame(data, columns=['Date', 'Platform', 'Product_Category', 'Comment_Text', 'Sentiment_Ground_Truth'])

# 5. Save to CSV
file_name = "swan_customer_feedback.csv"
df.to_csv(file_name, index=False)

print(f"✅ Success! Generated '{file_name}' with {len(df)} rows.")
print("Preview of the data:")
print(df.head())